server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: temple-donation-backend 
  datasource: 
    url: ${SUPABASE_DB_URL:jdbc:postgresql://db.supabase.co:5432/postgres}
    username: ${SUPABASE_DB_USER:postgres}
    password: ${SUPABASE_DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:your-email@gmail.com}
    password: ${EMAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

supabase:
  url: ${SUPABASE_URL:http://your-project.supabase.co}
  key: ${SUPABASE_ANON_KEY:}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:}

jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure}
  expiration: 86400000

logging: 
  level:
    com.temple: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} = %msg%n"
