server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: temple-donation-backend
  
  datasource:
    url: ${SUPABASE_DB_URL:jdbc:postgresql://db.supabase.co:5432/postgres}
    username: ${SUPABASE_DB_USER:postgres}
    password: ${SUPABASE_DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Supabase Configuration
supabase:
  url: ${SUPABASE_URL:https://your-project.supabase.co}
  anon-key: ${SUPABASE_ANON_KEY:}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:}
  storage:
    bucket: temple-images

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-jwt-secret-key-here-make-it-long-and-secure}
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://your-frontend-domain.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.temple: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# File Upload Configuration
file:
  upload:
    max-size: 10MB
    allowed-types: image/jpeg,image/png,image/webp
    upload-dir: ./uploads 